language: swift
osx_image: xcode10.1

before_install:
 - pod repo update
 - gem install xcpretty -N

 script: xcodebuild -workspace SouthernSales.xcworkspace -scheme SouthernSales -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c